# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PotLuck' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PotLuck

	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
        pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
pod 'Firebase/Storage'

  target 'PotLuckTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PotLuckUITests' do
    # Pods for testing
  end

end
